strictDepBuilds: false
allowBuilds:
  esbuild: true
  sharp: true
  secp256k1: true
  tiny-secp256k1: true
  bufferutil: true
  utf-8-validate: true
  blake-hash: true
  protobufjs: true
  unrs-resolver: true
  usb: false
